name: drn
channels:
- conda-forge
- bioconda
- nodefaults
dependencies:
- python =3.11.0
- snakemake =7.18.2
- graphviz =6.0.1
- scikit-learn =1.1.3
- pandas =1.5.1
- pyarrow =11.0.0
- scipy =1.9.3
- matplotlib =3.6.3
- statsmodels =0.13.5
- networkx =2.8.4
- seaborn =0.12.1
- colorcet =3.0.1
- munkres =1.1.4
- jupyterlab
- pip
- pip:
    - dysregnet ==0.0.4
- r-base =4.2.2
- r-data.table =1.14.6
- r-argparse =2.1.6
- bioconductor-deseq2 =1.38.0
- bioconductor-genie3 =1.20.0
- r-doparallel =1.0.17
- r-dorng =1.8.2
- bioconductor-lionessr =1.12.0
- r-arrow =11.0.0
- r-dplyr =1.1.1
- r-tidyr =1.3.0
- r-stringr =1.5.0
- bioconductor-summarizedexperiment =1.28.0
