
cluster:
  mkdir -p .snakemake/slurm_logs/{rule} &&
  sbatch
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-drn-{rule}
    --output=.snakemake/slurm_logs/{rule}/{rule}-%j.out
    --time=2-0:0:0
    --parsable
    --exclude {resources.exclude}
#--nodelist={resources.nodelist}

cluster-cancel: scancel
keep-going: True
local-cores: 20
latency-wait: 60
jobs: 20

use-conda: True
rerun-triggers: [mtime, params, input]
rerun-incomplete: True

default-resources:
  - partition=sesame_street
  - exclude="bert.exbio.wzw.tum.de"
  - mem_mb=20000
#  - nodelist="elmo.exbio.wzw.tum.de,ernie.exbio.wzw.tum.de,grover.exbio.wzw.tum.de,kermit.exbio.wzw.tum.de"

set-resources:
  - ssn:mem_mb=50000
  - clustering_benchmark_shared:mem_mb=50000
  - clustering_benchmark:mem_mb=50000
  - compute_overlap_shared:mem_mb=50000
  - compute_overlap:mem_mb=50000

resources:
  - io=2

