
cluster:
  mkdir -p .snakemake/slurm_logs/{rule} &&
  sbatch
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-drn-{rule}
    --output=.snakemake/slurm_logs/{rule}/{rule}-%j.out
    --time=2-0:0:0
    --parsable
#    --nodelist={resources.nodelist}

cluster-cancel: scancel
keep-going: True
local-cores: 20
latency-wait: 60
jobs: 20

use-conda: True
rerun-triggers: [mtime, params, input, software-env]
rerun-incomplete: True

default-resources:
  - partition=sesame_street
#  - nodelist="elmo.exbio.wzw.tum.de,ernie.exbio.wzw.tum.de,grover.exbio.wzw.tum.de,kermit.exbio.wzw.tum.de"
  - mem_mb=20000

set-resources:
  - ssn:mem_mb=50000

resources:
  - io=2

